//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace A06_Automobili.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("A06_Automobili.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap a06_lupa {
            get {
                object obj = ResourceManager.GetObject("a06_lupa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAD NURSE
        ///(c) 1986 Simon Pick
        ///
        ///An episode from a hospital near you...
        ///Scene: A tired trainee nurse carefully places the little bundle of joy into the 
        ///cot.
        ///NURSE: &apos;Now you be a good boy and go to sleep.&apos;
        ///BABY: &apos;Goooooooeeeeeeeagh&apos;
        ///NURSE: &apos;You won&apos;t jump out of the cot will you?&apos;
        ///BABY: &apos;Nnnnnnneeeeeeuuuuugh Slurp!&apos;
        ///NURSE: &apos;And you won&apos;t drink from the medicine bottles will you?&apos;
        ///BABY: &apos;Bleeeaaaaagh!&apos;
        ///NURSE: &apos;And you won&apos;t go near the lift now will you hmmm?&apos;
        ///BABY: &apos;Burp!&apos;
        ///NURSE: &apos;Pardon!  Don&apos;t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HelpDocs {
            get {
                return ResourceManager.GetString("HelpDocs", resourceCulture);
            }
        }
    }
}
